```{r results='asis', echo=FALSE}

github.organization <- "Terradue"
source('../R/global.R')

# load packages
suppressMessages(library("rjson"))
suppressMessages(library("RCurl"))  

# global chunk options
 opts_chunk$set(cache=FALSE, autodep=TRUE)

repo.frame <- GetRepos(github.organization)
```

# Terradue's guide to its OpenSource projects 


### Welcome !

blah blah

### A few facts

#### Top Starred repositories

```{r results='asis', echo=FALSE}

stars <- unique(repo.frame[ , which(names(repo.frame) %in% c("ProjectName","Stars"))])

stars <- stars[stars$Stars>0.0, ]

kable(head(stars[order(-stars$Stars), ], 5), format = "html")
```

#### Top Forked repositories

```{r results='asis', echo=FALSE}

forks <- unique(repo.frame[ , which(names(repo.frame) %in% c("ProjectName","Forks"))])

forks <- forks[forks$Forks>0.0, ]

kable(head(forks[order(-Forks$Forks), ], 5), format = "html")
```

#### Programming Languages

```{r results='asis', echo=FALSE}
pie(table(as.factor(repo.frame[ ,"ProgrammingLanguage"])))
```
