```{r results='asis', echo=FALSE}
opts_chunk$set(cache=FALSE, autodep=TRUE)
github.organization <- 'Terradue'
repo <- 'dcs-nest-coregistration'
language <- 'Shell'
creation <- '2014-07-01T06:41:00Z'
update <- '2014-09-04T05:58:25Z'
stars <- '1'
forks <- '0'
```
```{r results='asis', echo=FALSE}
url.organization <- paste0("https://github.com/", github.organization)
url.repo <- paste0(url.organization, "/", repo)
url.fork <- paste(url.organization, repo, "fork", sep="/")

url.star <- paste(url.organization, repo, "stargazers", sep="/")

link.star <- paste0("[", stars, "](", url.star, ")")

cat(paste0("[", github.organization, "](", url.organization, ") / [", repo, "](", url.repo, ")")) 
```

|    Language   | Created       | Last update | Stars         | Forks      | 
|:-------------:|---------------|-------------|---------------|------------|
| `r language`  | `r creation`  | `r update`  | `r     stars` | `r forks`  |


```{r results='asis', echo=FALSE}
suppressMessages(library("RCurl"))

cat(getURL(paste0("https://raw.githubusercontent.com/", github.organization, "/", repo, "/master/README.md")))
```

