```{r results='asis', echo=FALSE}
opts_chunk$set(cache=FALSE, autodep=TRUE)
github.organization <- 'Terradue'
repo <- 'dcs-beam-algalbloom'
language <- 'Shell'
creation <- '2014-06-19T12:32:36Z'
update <- '2014-09-04T06:13:09Z'
stars <- '1'
forks <- '2'
```
```{r results='asis', echo=FALSE}
url.organization <- paste0("https://github.com/", github.organization)
url.repo <- paste0(url.organization, "/", repo)
url.forks <- paste(url.organization, repo, "network", sep="/")

url.stars <- paste(url.organization, repo, "stargazers", sep="/")

link.stars <- paste0("[", stars, "](", url.stars, ")")
link.forks <- paste0("[", forks, "](", url.forks, ")")

cat(paste0("[", github.organization, "](", url.organization, ") / [", repo, "](", url.repo, ")")) 
```

|    Language   | Created       | Last update | Stars          | Forks          | 
|:-------------:|:-------------:|:-----------:|:--------------:|:--------------:|
| `r language`  | `r creation`  | `r update`  | `r link.stars` | `r link.forks` |


```{r results='asis', echo=FALSE}
suppressMessages(library("RCurl"))

cat(getURL(paste0("https://raw.githubusercontent.com/", github.organization, "/", repo, "/master/README.md")))
```

