```{r results='asis', echo=FALSE}

github.organization <- "Terradue"
```

```{r results='asis', echo=FALSE}
# load packages
suppressMessages(library("rjson"))
suppressMessages(library("RCurl"))  

# global chunk options
opts_chunk$set(cache=FALSE, autodep=TRUE)
```

# Summary

```{r results='asis', echo=FALSE}

# get the data from GitHub
repos.json<-fromJSON(getURLContent(paste0("https://api.github.com/orgs/", github.organization, "/repos?per_page=1000"), ssl.verifypeer = FALSE, useragent = "R"))

project.name <- c()
project.fullname <- c()
project.description <- c()
project.lastupdate <- c()
project.creationdate <- c()
project.language <- c()
project.chapter <- c()


# create a dataframe with the repos

for(i in 1:length(repos.json))
  {
  repo<-repos.json[[i]]
  if(repo$private==FALSE)
    {
    gitBook.filepath <- paste("https://raw.githubusercontent.com", repo$full_name, "master/.gitbook",sep="/")
    #print(gitBook.filepath)
    # build the .gitbook file path for each repository
    # to do: how to hide the error message?
    result <- try(section.json <-fromJSON(getURLContent(gitBook.filepath, ssl.verifypeer = FALSE, useragent = "R")));
    if(class(result) == "try-error") 
      next;
    
    
    # a repo can be part of more then one section
    for(j in 1:length(section.json))
      {
      project.name <- append(project.name, repo$name)
      project.fullname <- append(project.fullname, repo$full_name)
      project.description <- append(project.description, repo$description)
      project.lastupdate <- append(project.lastupdate, repo$updated_at)
      project.creationdate  <- append(project.creationdate , repo$created_at)
      project.language <- append(project.language, ifelse(length(repo$language)>0,repo$language,"")) 
      project.chapter <- append(project.chapter, section.json[[j]])  
      }
    }
  }


repo.frame <- data.frame(ProjectName=project.name, 
  Description=project.description, 
  ProgrammingLanguage=project.language,
  LastTimeUpdate=project.lastupdate,
  CreationTimeDate=project.creationdate, 
  Chapter=project.chapter,
  ProjectFullName=project.fullname,
  stringsAsFactors = FALSE)

# build the page with reference link 
template <- "template/repo.Rmd"

# chapters... the first level of the ToC
# get the chapters from the configuration
config.json <- fromJSON(file=".config.json")

chapters <- c()
for(i in 1:length(config.json))
  chapters <- append(chapters, config.json[i]$chapter$title)

# create a folder for the sections of the book
dir.create("section", showWarnings = FALSE)

for(i in chapters)
  {
  chapter.frame <- repo.frame[repo.frame$Chapter==i, ]
  chapter.frame <- chapter.frame[order(chapter.frame$ProjectName), ]
  
  # add the chapter entry in the ToC
  cat(paste0("* [", i, "](chapter/", gsub(" ", "-", i), ".md)\n"))
  
  # loop through the repos of the chapter
  for(j in seq(nrow(chapter.frame))) {
    
    repo <- chapter.frame[j, ]$ProjectName 
    
    # add the section entry in the ToC
    cat(paste0(" * [", repo, "](section/", repo, ".md)\n"))
    
    # get the repo information 
    repo.declaration <- paste0("repo <- '", repo, "'")
    language.declaration <- paste0("language <- '", chapter.frame[j, ]$ProgrammingLanguage, "'")	
    creation.declaration <- paste0("creation <- '", chapter.frame[j, ]$CreationTimeDate, "'")  
    update.declaration <- paste0("update <- '", chapter.frame[j, ]$LastTimeUpdate, "'")  
    organization.declaration <- paste0("github.organization <- '", github.organization, "'")
    
    # create the section Rmd file
    fileConn <- file(paste0("section/", repo, ".Rmd"))   
    
    content <- c("```{r results='asis', echo=FALSE}",
      "opts_chunk$set(cache=FALSE, autodep=TRUE)",
      repo.declaration,
      language.declaration,
      creation.declaration,
      update.declaration,
      organization.declaration,
      "```",
      readChar(template, file.info(template)$size)) 
    
    writeLines(content, fileConn)
    close(fileConn)     
    }
  }
```

