## C Sharp libraries
DotNet4One
DotNetEarthObservation
DotNetGeoJson
DotNetOpenSearch
DotNetOpenSearchKml
DotNetOpenSearchTumblr
DotNetSentinelSafe
DotNetSyndication
DotNet4One
DotNetEarthObservation
DotNetGeoJson
DotNetOpenSearch
DotNetOpenSearchKml
DotNetOpenSearchTumblr
DotNetSentinelSafe
DotNetSyndication
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
   <th align="left"> LastTimeUpdate </th>
   <th align="left"> CreationTimeDate </th>
   <th align="left"> Chapter </th>
   <th align="left"> ProjectFullName </th>
   <th align="right"> Forks </th>
   <th align="right"> Stars </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> DotNet4One </td>
   <td align="left"> .Net Library to Access XML-RPC API of Opennebula </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:52:58Z </td>
   <td align="left"> 2014-07-01T14:32:22Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNet4One </td>
   <td align="right"> 1 </td>
   <td align="right"> 4 </td>
  </tr>
  <tr>
   <td align="left"> DotNetEarthObservation </td>
   <td align="left"> .Net C# library implementing the Earth Observation Metadata profile of Observations &  Measurements </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-02T19:20:31Z </td>
   <td align="left"> 2014-05-28T15:22:30Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetEarthObservation </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNetGeoJson </td>
   <td align="left"> GeoJson library for .Net </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:21:00Z </td>
   <td align="left"> 2014-04-14T08:21:59Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetGeoJson </td>
   <td align="right"> 3 </td>
   <td align="right"> 1 </td>
  </tr>
  <tr>
   <td align="left"> DotNetOpenSearch </td>
   <td align="left"> OpenSearch library for .Net </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-02T19:21:13Z </td>
   <td align="left"> 2014-04-10T06:56:27Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetOpenSearch </td>
   <td align="right"> 1 </td>
   <td align="right"> 1 </td>
  </tr>
  <tr>
   <td align="left"> DotNetOpenSearchKml </td>
   <td align="left"> KML OpenSearch extension library for .Net </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-02T19:21:28Z </td>
   <td align="left"> 2014-06-24T14:24:17Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetOpenSearchKml </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNetOpenSearchTumblr </td>
   <td align="left"> Tumblr OpenSearch extension library for .Net </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-03T10:10:15Z </td>
   <td align="left"> 2014-07-01T14:39:55Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetOpenSearchTumblr </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNetSentinelSafe </td>
   <td align="left"> .Net library and tools to manipulate Sentinel product and metadata in SAFE format </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:20:32Z </td>
   <td align="left"> 2014-08-29T09:13:25Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetSentinelSafe </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNetSyndication </td>
   <td align="left"> Web ServiceModel </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:21:20Z </td>
   <td align="left"> 2014-05-27T06:24:01Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetSyndication </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
</tbody>
</table>
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
   <th align="left"> LastTimeUpdate </th>
   <th align="left"> CreationTimeDate </th>
   <th align="left"> Chapter </th>
   <th align="left"> ProjectFullName </th>
   <th align="right"> Forks </th>
   <th align="right"> Stars </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> DotNet4One </td>
   <td align="left"> .Net Library to Access XML-RPC API of Opennebula </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:52:58Z </td>
   <td align="left"> 2014-07-01T14:32:22Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNet4One </td>
   <td align="right"> 1 </td>
   <td align="right"> 4 </td>
  </tr>
  <tr>
   <td align="left"> DotNetEarthObservation </td>
   <td align="left"> .Net C# library implementing the Earth Observation Metadata profile of Observations &  Measurements </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-02T19:20:31Z </td>
   <td align="left"> 2014-05-28T15:22:30Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetEarthObservation </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNetGeoJson </td>
   <td align="left"> GeoJson library for .Net </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:21:00Z </td>
   <td align="left"> 2014-04-14T08:21:59Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetGeoJson </td>
   <td align="right"> 3 </td>
   <td align="right"> 1 </td>
  </tr>
  <tr>
   <td align="left"> DotNetOpenSearch </td>
   <td align="left"> OpenSearch library for .Net </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-02T19:21:13Z </td>
   <td align="left"> 2014-04-10T06:56:27Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetOpenSearch </td>
   <td align="right"> 1 </td>
   <td align="right"> 1 </td>
  </tr>
  <tr>
   <td align="left"> DotNetOpenSearchKml </td>
   <td align="left"> KML OpenSearch extension library for .Net </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-02T19:21:28Z </td>
   <td align="left"> 2014-06-24T14:24:17Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetOpenSearchKml </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNetOpenSearchTumblr </td>
   <td align="left"> Tumblr OpenSearch extension library for .Net </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-03T10:10:15Z </td>
   <td align="left"> 2014-07-01T14:39:55Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetOpenSearchTumblr </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNetSentinelSafe </td>
   <td align="left"> .Net library and tools to manipulate Sentinel product and metadata in SAFE format </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:20:32Z </td>
   <td align="left"> 2014-08-29T09:13:25Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetSentinelSafe </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNetSyndication </td>
   <td align="left"> Web ServiceModel </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:21:20Z </td>
   <td align="left"> 2014-05-27T06:24:01Z </td>
   <td align="left"> C Sharp </td>
   <td align="left"> Terradue/DotNetSyndication </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
</tbody>
</table>
