## Developer Cloud Sandbox field guide
dcs-beam-algalbloom
dcs-beam-flh-java
dcs-nest-coregistration
dcs-python-ndvi
dcs-r-gbifsst
dcs-beam-algalbloom
dcs-beam-flh-java
dcs-nest-coregistration
dcs-python-ndvi
dcs-r-gbifsst
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
   <th align="left"> LastTimeUpdate </th>
   <th align="left"> CreationTimeDate </th>
   <th align="left"> Chapter </th>
   <th align="left"> ProjectFullName </th>
   <th align="right"> Forks </th>
   <th align="right"> Stars </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> dcs-beam-algalbloom </td>
   <td align="left">  </td>
   <td align="left"> Shell </td>
   <td align="left"> 2014-09-04T06:13:09Z </td>
   <td align="left"> 2014-06-19T12:32:36Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-beam-algalbloom </td>
   <td align="right"> 2 </td>
   <td align="right"> 1 </td>
  </tr>
  <tr>
   <td align="left"> dcs-beam-flh-java </td>
   <td align="left"> BEAM Java tutorial to implement a BEAM Operator to calculate the Fluorescence line height in Envisat MERIS Level 1b products on the Developer Cloud Sandbox </td>
   <td align="left"> Shell </td>
   <td align="left"> 2014-09-04T14:22:52Z </td>
   <td align="left"> 2014-05-07T14:37:46Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-beam-flh-java </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> dcs-nest-coregistration </td>
   <td align="left"> Developer Cloud Sandbox NEST Coregistration tutorial - ERS Tandem </td>
   <td align="left"> Shell </td>
   <td align="left"> 2014-09-04T05:58:25Z </td>
   <td align="left"> 2014-07-01T06:41:00Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-nest-coregistration </td>
   <td align="right"> 0 </td>
   <td align="right"> 1 </td>
  </tr>
  <tr>
   <td align="left"> dcs-python-ndvi </td>
   <td align="left"> Developer Cloud Sandbox Python tutorial - Landsat NDVI </td>
   <td align="left"> Python </td>
   <td align="left"> 2014-09-04T14:22:30Z </td>
   <td align="left"> 2014-06-17T11:08:49Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-python-ndvi </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> dcs-r-gbifsst </td>
   <td align="left">  </td>
   <td align="left"> R </td>
   <td align="left"> 2014-09-04T07:40:19Z </td>
   <td align="left"> 2014-06-20T07:11:11Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-r-gbifsst </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
</tbody>
</table>
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
   <th align="left"> LastTimeUpdate </th>
   <th align="left"> CreationTimeDate </th>
   <th align="left"> Chapter </th>
   <th align="left"> ProjectFullName </th>
   <th align="right"> Forks </th>
   <th align="right"> Stars </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> dcs-beam-algalbloom </td>
   <td align="left">  </td>
   <td align="left"> Shell </td>
   <td align="left"> 2014-09-04T06:13:09Z </td>
   <td align="left"> 2014-06-19T12:32:36Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-beam-algalbloom </td>
   <td align="right"> 2 </td>
   <td align="right"> 1 </td>
  </tr>
  <tr>
   <td align="left"> dcs-beam-flh-java </td>
   <td align="left"> BEAM Java tutorial to implement a BEAM Operator to calculate the Fluorescence line height in Envisat MERIS Level 1b products on the Developer Cloud Sandbox </td>
   <td align="left"> Shell </td>
   <td align="left"> 2014-09-04T14:22:52Z </td>
   <td align="left"> 2014-05-07T14:37:46Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-beam-flh-java </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> dcs-nest-coregistration </td>
   <td align="left"> Developer Cloud Sandbox NEST Coregistration tutorial - ERS Tandem </td>
   <td align="left"> Shell </td>
   <td align="left"> 2014-09-04T05:58:25Z </td>
   <td align="left"> 2014-07-01T06:41:00Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-nest-coregistration </td>
   <td align="right"> 0 </td>
   <td align="right"> 1 </td>
  </tr>
  <tr>
   <td align="left"> dcs-python-ndvi </td>
   <td align="left"> Developer Cloud Sandbox Python tutorial - Landsat NDVI </td>
   <td align="left"> Python </td>
   <td align="left"> 2014-09-04T14:22:30Z </td>
   <td align="left"> 2014-06-17T11:08:49Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-python-ndvi </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> dcs-r-gbifsst </td>
   <td align="left">  </td>
   <td align="left"> R </td>
   <td align="left"> 2014-09-04T07:40:19Z </td>
   <td align="left"> 2014-06-20T07:11:11Z </td>
   <td align="left"> DCS Field Guide </td>
   <td align="left"> Terradue/dcs-r-gbifsst </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
</tbody>
</table>
