## OpenNebula
abiquo-cli
abiquo4one
DotNet4One
dsi4one
jclouds4one
jCloudSigma
abiquo-cli
abiquo4one
DotNet4One
dsi4one
jclouds4one
jCloudSigma
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
   <th align="left"> LastTimeUpdate </th>
   <th align="left"> CreationTimeDate </th>
   <th align="left"> Chapter </th>
   <th align="left"> ProjectFullName </th>
   <th align="right"> Forks </th>
   <th align="right"> Stars </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> abiquo-cli </td>
   <td align="left"> jclouds-labs-cli is a command line tool that allows you to interact with jclouds LABS part of the library </td>
   <td align="left"> Java </td>
   <td align="left"> 2014-09-04T14:24:27Z </td>
   <td align="left"> 2013-09-05T10:00:47Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/abiquo-cli </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> abiquo4one </td>
   <td align="left"> Abiquo driver for Opennebula </td>
   <td align="left"> Ruby </td>
   <td align="left"> 2014-09-04T14:24:01Z </td>
   <td align="left"> 2013-11-18T14:16:57Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/abiquo4one </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNet4One </td>
   <td align="left"> .Net Library to Access XML-RPC API of Opennebula </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:52:58Z </td>
   <td align="left"> 2014-07-01T14:32:22Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/DotNet4One </td>
   <td align="right"> 1 </td>
   <td align="right"> 4 </td>
  </tr>
  <tr>
   <td align="left"> dsi4one </td>
   <td align="left"> T-Systems DSI driver for Opennebula </td>
   <td align="left"> Ruby </td>
   <td align="left"> 2014-09-04T14:23:33Z </td>
   <td align="left"> 2013-03-25T08:59:53Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/dsi4one </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> jclouds4one </td>
   <td align="left"> jclouds driver for OpenNebula </td>
   <td align="left"> Shell </td>
   <td align="left"> 2014-09-04T14:24:48Z </td>
   <td align="left"> 2013-09-26T12:52:26Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/jclouds4one </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> jCloudSigma </td>
   <td align="left"> ONE driver for CloudSigma </td>
   <td align="left"> Java </td>
   <td align="left"> 2014-09-04T14:21:48Z </td>
   <td align="left"> 2014-06-19T14:56:24Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/jCloudSigma </td>
   <td align="right"> 0 </td>
   <td align="right"> 1 </td>
  </tr>
</tbody>
</table>
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
   <th align="left"> LastTimeUpdate </th>
   <th align="left"> CreationTimeDate </th>
   <th align="left"> Chapter </th>
   <th align="left"> ProjectFullName </th>
   <th align="right"> Forks </th>
   <th align="right"> Stars </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> abiquo-cli </td>
   <td align="left"> jclouds-labs-cli is a command line tool that allows you to interact with jclouds LABS part of the library </td>
   <td align="left"> Java </td>
   <td align="left"> 2014-09-04T14:24:27Z </td>
   <td align="left"> 2013-09-05T10:00:47Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/abiquo-cli </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> abiquo4one </td>
   <td align="left"> Abiquo driver for Opennebula </td>
   <td align="left"> Ruby </td>
   <td align="left"> 2014-09-04T14:24:01Z </td>
   <td align="left"> 2013-11-18T14:16:57Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/abiquo4one </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> DotNet4One </td>
   <td align="left"> .Net Library to Access XML-RPC API of Opennebula </td>
   <td align="left"> C# </td>
   <td align="left"> 2014-09-04T14:52:58Z </td>
   <td align="left"> 2014-07-01T14:32:22Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/DotNet4One </td>
   <td align="right"> 1 </td>
   <td align="right"> 4 </td>
  </tr>
  <tr>
   <td align="left"> dsi4one </td>
   <td align="left"> T-Systems DSI driver for Opennebula </td>
   <td align="left"> Ruby </td>
   <td align="left"> 2014-09-04T14:23:33Z </td>
   <td align="left"> 2013-03-25T08:59:53Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/dsi4one </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> jclouds4one </td>
   <td align="left"> jclouds driver for OpenNebula </td>
   <td align="left"> Shell </td>
   <td align="left"> 2014-09-04T14:24:48Z </td>
   <td align="left"> 2013-09-26T12:52:26Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/jclouds4one </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> jCloudSigma </td>
   <td align="left"> ONE driver for CloudSigma </td>
   <td align="left"> Java </td>
   <td align="left"> 2014-09-04T14:21:48Z </td>
   <td align="left"> 2014-06-19T14:56:24Z </td>
   <td align="left"> OpenNebula </td>
   <td align="left"> Terradue/jCloudSigma </td>
   <td align="right"> 0 </td>
   <td align="right"> 1 </td>
  </tr>
</tbody>
</table>
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> abiquo-cli </td>
   <td align="left"> jclouds-labs-cli is a command line tool that allows you to interact with jclouds LABS part of the library </td>
   <td align="left"> Java </td>
  </tr>
  <tr>
   <td align="left"> abiquo4one </td>
   <td align="left"> Abiquo driver for Opennebula </td>
   <td align="left"> Ruby </td>
  </tr>
  <tr>
   <td align="left"> DotNet4One </td>
   <td align="left"> .Net Library to Access XML-RPC API of Opennebula </td>
   <td align="left"> C# </td>
  </tr>
  <tr>
   <td align="left"> dsi4one </td>
   <td align="left"> T-Systems DSI driver for Opennebula </td>
   <td align="left"> Ruby </td>
  </tr>
  <tr>
   <td align="left"> jclouds4one </td>
   <td align="left"> jclouds driver for OpenNebula </td>
   <td align="left"> Shell </td>
  </tr>
  <tr>
   <td align="left"> jCloudSigma </td>
   <td align="left"> ONE driver for CloudSigma </td>
   <td align="left"> Java </td>
  </tr>
</tbody>
</table>
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> abiquo-cli </td>
   <td align="left"> jclouds-labs-cli is a command line tool that allows you to interact with jclouds LABS part of the library </td>
   <td align="left"> Java </td>
  </tr>
  <tr>
   <td align="left"> abiquo4one </td>
   <td align="left"> Abiquo driver for Opennebula </td>
   <td align="left"> Ruby </td>
  </tr>
  <tr>
   <td align="left"> DotNet4One </td>
   <td align="left"> .Net Library to Access XML-RPC API of Opennebula </td>
   <td align="left"> C# </td>
  </tr>
  <tr>
   <td align="left"> dsi4one </td>
   <td align="left"> T-Systems DSI driver for Opennebula </td>
   <td align="left"> Ruby </td>
  </tr>
  <tr>
   <td align="left"> jclouds4one </td>
   <td align="left"> jclouds driver for OpenNebula </td>
   <td align="left"> Shell </td>
  </tr>
  <tr>
   <td align="left"> jCloudSigma </td>
   <td align="left"> ONE driver for CloudSigma </td>
   <td align="left"> Java </td>
  </tr>
</tbody>
</table>
