## R packages
rLandsat8
rOpenSearch
rLandsat8
rOpenSearch
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
   <th align="left"> LastTimeUpdate </th>
   <th align="left"> CreationTimeDate </th>
   <th align="left"> Chapter </th>
   <th align="left"> ProjectFullName </th>
   <th align="right"> Forks </th>
   <th align="right"> Stars </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> rLandsat8 </td>
   <td align="left"> R package to process USGS Landsat 8 data </td>
   <td align="left"> R </td>
   <td align="left"> 2014-09-02T12:23:40Z </td>
   <td align="left"> 2014-09-01T07:25:16Z </td>
   <td align="left"> R packages </td>
   <td align="left"> Terradue/rLandsat8 </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> rOpenSearch </td>
   <td align="left"> R interface to OpenSearch </td>
   <td align="left"> R </td>
   <td align="left"> 2014-09-04T07:47:46Z </td>
   <td align="left"> 2014-05-29T06:37:53Z </td>
   <td align="left"> R packages </td>
   <td align="left"> Terradue/rOpenSearch </td>
   <td align="right"> 0 </td>
   <td align="right"> 2 </td>
  </tr>
</tbody>
</table>
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
   <th align="left"> LastTimeUpdate </th>
   <th align="left"> CreationTimeDate </th>
   <th align="left"> Chapter </th>
   <th align="left"> ProjectFullName </th>
   <th align="right"> Forks </th>
   <th align="right"> Stars </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> rLandsat8 </td>
   <td align="left"> R package to process USGS Landsat 8 data </td>
   <td align="left"> R </td>
   <td align="left"> 2014-09-02T12:23:40Z </td>
   <td align="left"> 2014-09-01T07:25:16Z </td>
   <td align="left"> R packages </td>
   <td align="left"> Terradue/rLandsat8 </td>
   <td align="right"> 0 </td>
   <td align="right"> 0 </td>
  </tr>
  <tr>
   <td align="left"> rOpenSearch </td>
   <td align="left"> R interface to OpenSearch </td>
   <td align="left"> R </td>
   <td align="left"> 2014-09-04T07:47:46Z </td>
   <td align="left"> 2014-05-29T06:37:53Z </td>
   <td align="left"> R packages </td>
   <td align="left"> Terradue/rOpenSearch </td>
   <td align="right"> 0 </td>
   <td align="right"> 2 </td>
  </tr>
</tbody>
</table>
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> rLandsat8 </td>
   <td align="left"> R package to process USGS Landsat 8 data </td>
   <td align="left"> R </td>
  </tr>
  <tr>
   <td align="left"> rOpenSearch </td>
   <td align="left"> R interface to OpenSearch </td>
   <td align="left"> R </td>
  </tr>
</tbody>
</table>
<table>
 <thead>
  <tr>
   <th align="left"> ProjectName </th>
   <th align="left"> Description </th>
   <th align="left"> ProgrammingLanguage </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td align="left"> rLandsat8 </td>
   <td align="left"> R package to process USGS Landsat 8 data </td>
   <td align="left"> R </td>
  </tr>
  <tr>
   <td align="left"> rOpenSearch </td>
   <td align="left"> R interface to OpenSearch </td>
   <td align="left"> R </td>
  </tr>
</tbody>
</table>
